fix: add missing ghc-platform to cabal.project.stage1
The refactoring in 'reorganize cabal.project files' accidentally removed
libraries/ghc-platform from cabal.project.stage1. This package is required
because ghc-boot depends on ghc-platform >= 0.1.

Without this fix, all CI builds fail with:
  Error: [Cabal-7107]
  Could not resolve dependencies:
  unknown package: host:ghc-platform (dependency of host:ghc-boot)